apiVersion: apps/v1
kind: Deployment
metadata:
  name: webos
  labels:
    app: webos
spec:
  selector:
    matchLabels:
      app: webos
  replicas: 3
  template:
    metadata:
      labels:
        app: webos
    spec:
      containers:
      - image: demetrix/httpd:latest
        name: webos
        ports:
        - containerPort: 80
          name: webos
